### ISSUE TITLE
OpenAI API Key leaked

### ISSUE THREAD

**Issue by thisislvca** [cindy-x-liang/Outfit-App---tackon#1]
Hey! You leaked your own OpenAI API key.

https://github.com/cindy-x-liang/Outfit-App---tackon/blob/b782239eacc0fd97b4f5a401d0292076fa55176b/app2/env.txt

Not sure why you'd keep your env variables in a txt file :laughing:

**Comment by thisislvca** [comment]
@cindy-x-liang I'd also rotate the key cuz ppl can go back and still see it in the commits history :)

**Comment by cindy-x-liang** [comment]
@thisislvca thanks!
